spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.232.197.191:3306/secondaryhouse?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: secondaryHouse
    password: 2JxWMnNFX4sbPXih
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8181
mybatis:
  mapper-locations: classpath*:resources/mapper/*.xml
  type-aliases-package: com.springboot.secondaryHouse.dao